name: Update ECS image
description: Redeploy ECS service with the latest image

runs:
  using: "composite"

  steps:
    - name: Checkout Infrastructure Repo
      uses: actions/checkout@v4

    - name: Print GitHub workspace
      shell: bash
      run: echo "Current directory: ${{ github.workspace }}"

    - name: Configure AWS Credentials and Assume Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ECS_ROLE_ARN }}
        role-session-name: DeployWebService

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.4

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ github.workspace }}/infrastructure
      shell: bash

    - name: Terraform Plan with Target
      run: terraform plan -target=module.web_service -out=plan.out -input=false
      working-directory: ${{ github.workspace }}/infrastructure
      shell: bash

    - name: Terraform Apply with Target
      run: terraform apply "plan.out" -auto-approve -input=false
      working-directory: ${{ github.workspace }}/infrastructure
      shell: bash