name: Deploy Web Service

on:
  repository_dispatch:
    types: [deploy_web_service]

jobs:
  deploy_web_service:
    # Don't run this job if the image tag and secrets are not provided
    if: >
      github.event.client_payload.image_tag != null && 
      github.event.client_payload.image_tag != '' && 
      github.event.client_payload.secrets != null && 
      github.event.client_payload.secrets != ''

    permissions:
      contents: read
      id-token: write
      
    uses: ./.github/workflows/terraform_apply.yml
    
    with:
      environment: ${{ github.event.client_payload.environment }}
      web_service_image_tag: ${{ github.event.client_payload.image_tag }}
      web_service_secrets: '${{ toJson(github.event.client_payload.secrets) }}'

    secrets:
      aws_ecs_role_arn: ${{ secrets.AWS_ECS_ROLE_ARN }}
      hosted_zone_id: ${{ secrets.TF_VAR_HOSTED_ZONE_ID }}