name: Deploy Web Service

on:
  repository_dispatch:
    types: [deploy_web_service]

jobs:
  echo:
    env:
      toPrint: toJSON(${{ github.event.client_payload.secrets }})
    runs-on: ubuntu-latest
    steps:
      - run: |
          json_array="${{ github.event.client_payload.secrets }}"
          for item in $(echo "$json_array" | jq -r '.[]'); do
            echo "Item: $item"
          done

  deploy_web_service:
    # Don't run this job if the image tag and secrets are not provided
    if: >
      github.event.client_payload.image_tag != null && 
      github.event.client_payload.image_tag != '' && 
      github.event.client_payload.secrets != null && 
      github.event.client_payload.secrets != ''

    permissions:
      contents: read
      id-token: write
      
    uses: ./.github/workflows/terraform_apply.yml
    
    with:
      environment: ${{ github.event.client_payload.environment }}
      web_service_image_tag: ${{ github.event.client_payload.image_tag }}

    secrets:
      web_service_secrets: toJSON(${{ github.event.client_payload.secrets }})
      aws_ecs_role_arn: ${{ secrets.AWS_ECS_ROLE_ARN }}
      hosted_zone_id: ${{ secrets.TF_VAR_HOSTED_ZONE_ID }}