name: Deploy Core Server

on:
  repository_dispatch:
    types: [deploy_core_server]

jobs:
  deploy_web_service:
    # Don't run this job if the image tag is not provided
    if: >
      github.event.client_payload.image_tag != null && 
      github.event.client_payload.image_tag != '' && 
      github.event.client_payload.secrets != null && 
      github.event.client_payload.secrets != ''

    permissions:
      contents: read
      id-token: write
      
    uses: ./.github/workflows/terraform_apply.yml
    
    with:
      environment: ${{ github.event.client_payload.environment }}
      core_server_image_tag: ${{ github.event.client_payload.image_tag }}

    secrets:
      aws_ecs_role_arn: ${{ secrets.AWS_ECS_ROLE_ARN }}
      core_server_secrets: ${{ github.event.client_payload.secrets }}
      hosted_zone_id: ${{ secrets.TF_VAR_HOSTED_ZONE_ID }}