name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: development
      core_server_image_tag:
        type: string
        required: false
      web_service_image_tag:
        type: string
        required: false

    secrets:
      aws_ecs_role_arn:
        required: true
      core_rds_username:
        required: true
      core_rds_password:
        required: true
      hosted_zone_id:
        required: true

concurrency:
  group: "terraform_apply-${{ inputs.environment }}"
  cancel-in-progress: false
        
env:
  AWS_REGION: us-west-2
  AWS_ECS_ROLE_ARN: ${{ secrets.AWS_ECS_ROLE_ARN }}
  TF_VAR_core_rds_username: ${{ secrets.core_rds_username }}
  TF_VAR_core_rds_password: ${{ secrets.core_rds_password }}
  TF_VAR_hosted_zone_id: ${{ secrets.hosted_zone_id }}
  ENVIRONMENT: ${{ inputs.environment }}
  TF_VAR_web_service_image_tag: ${{ inputs.web_service_image_tag }}
  TF_VAR_core_server_image_tag: ${{ inputs.core_server_image_tag }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials and Assume Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ECS_ROLE_ARN }}
          role-session-name: DeployWebService

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Get old web image tag
        run: |
          echo "TF_VAR_old_web_service_image_tag=$(terraform output -raw web_image_tag)" >> $GITHUB_ENV

      - name: Get old core server image tag
        run: |
          echo "TF_VAR_old_core_server_image_tag=$(terraform output -raw core_server_image_tag)" >> $GITHUB_ENV

      - name: Terraform Plan
        run: terraform plan -out=plan.out

      - name: Terraform Apply
        run: terraform apply -lock-timeout=5m -auto-approve -input=false plan.out
          
          
