name: Manually Trigger Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        required: false
        default: development
      core_server_image_tag:
        required: false
      web_service_image_tag:
        required: false

jobs:
  trigger_terraform_apply:
    permissions:
      contents: read
      id-token: write
      
    uses: ./.github/workflows/terraform_apply.yml

    with:
      environment: ${{ inputs.environment }}
      web_service_image_tag: ${{ inputs.web_service_image_tag }}
      core_server_image_tag: ${{ inputs.core_server_image_tag }}
      
    secrets:   
      aws_ecs_role_arn: ${{ secrets.AWS_ECS_ROLE_ARN }}
      hosted_zone_id: ${{ secrets.TF_VAR_HOSTED_ZONE_ID }}