name: Trigger Terraform Apply on Web's ECS Cluster

on:
  repository_dispatch:
    types: [redeploy_web_service]

  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: development
      image_tag:
        required: true
      region:
        required: true
        default: us-west-2

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ github.event.inputs.region }}
      AWS_ECS_ROLE_ARN: ${{ secrets.AWS_ECS_ROLE_ARN }}
      IMAGE_TAG: ${{ github.event.inputs.image_tag }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Infrastructure Repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/update_ecs_image
        with:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ECS_ROLE_ARN: ${{ env.AWS_ECS_ROLE_ARN }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          
          
